version: '2'
services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: DATABASE_USERNAME
      POSTGRES_PASSWORD: DATABASE_PASSWORD
  web:
    image: juliolustosa/ruby-rails
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
